export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const REGISTER_USER = 'REGISTER_USER';
export const SET_TAB_INDEX_PRICING = 'SET_TAB_INDEX_PRICING';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
